// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr6pP6FbWedzSTJnDTv0yO6TsfHKItLLU',
    appId: '1:187467720629:web:ee6cf3a4ff558167675bfc',
    messagingSenderId: '187467720629',
    projectId: 'googol-1e100',
    authDomain: 'googol-1e100.firebaseapp.com',
    storageBucket: 'googol-1e100.appspot.com',
    measurementId: 'G-FWY9VVSN4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkIDKPe9bexEEj86pX5UQk9MK4fE-Awk',
    appId: '1:187467720629:android:be5383b486e63e6b675bfc',
    messagingSenderId: '187467720629',
    projectId: 'googol-1e100',
    storageBucket: 'googol-1e100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUl2V1UvSpfaF8jHZSBYLd1UvpbLlRixE',
    appId: '1:187467720629:ios:889d6f7c6f80594b675bfc',
    messagingSenderId: '187467720629',
    projectId: 'googol-1e100',
    storageBucket: 'googol-1e100.appspot.com',
    iosClientId: '187467720629-kgbjecqsf1f6hcotuqtdic25fjdk7kls.apps.googleusercontent.com',
    iosBundleId: 'com.example.binBrain',
  );
}
